// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh.hans');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "添加注釋";
Blockly.Msg.AUTH = "請授權這個應用程式以保存您的作品並共用。";
Blockly.Msg.CHANGE_VALUE_TITLE = "更改值：";
Blockly.Msg.CHAT = "通過在此框輸入與您的合作者溝通！";
Blockly.Msg.CLEAN_UP = "清理塊";
Blockly.Msg.COLLAPSE_ALL = "折疊塊";
Blockly.Msg.COLLAPSE_BLOCK = "折疊塊";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "顏色1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "顏色2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "用一個給定的比率(0.0-1.0)混合兩種顏色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/顏色";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "從調色板中選擇一種顏色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "隨機顏色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "隨機選擇一種顏色。";
Blockly.Msg.COLOUR_RGB_BLUE = "藍色";
Blockly.Msg.COLOUR_RGB_GREEN = "綠色";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "紅色";
Blockly.Msg.COLOUR_RGB_TITLE = "顏色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "通過指定紅色、綠色和藍色的量創建一種顏色。所有的值必須介於0和100之間。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "中斷迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "繼續下一次迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "中斷包含它的迴圈。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳過這個迴圈的剩餘部分，並繼續下一次反覆運算。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告：此塊僅可用於在一個迴圈內。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "為每個項目 %1 在列表中 %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍歷每個清單中的專案，將變數“%1”設定到該項中，然後執行某些語句。";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "使用 %1 從範圍 %2 到 %3 每隔 %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "從起始數到結尾數中取出變數“%1”的值，按指定的時間間隔，執行指定的塊。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "在if語句塊中增加一個條件。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "添加一個最終的，包括所有情況的節到if塊中。";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "增加、刪除或重新排列各節來重新配置“if”塊。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否則";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否則如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "如果值為真，執行一些語句。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "如果值為真，則執行語句的第一塊。否則，則執行語句的第二塊。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一個值為真，則執行語句的第一個塊。否則，如果第二個值為真，則執行語句的第二塊。";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一個值為真，則執行語句的第一塊。否則，如果第二個值為真，則執行語句的第二塊。如果沒有值為真，則執行語句的最後一塊。";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For迴圈";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "執行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重複 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次執行一些語句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重複直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重複當";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "只要值為假，執行一些語句。";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "只要值為真，執行一些語句。";
Blockly.Msg.DELETE_ALL_BLOCKS = "刪除所有%1塊嗎？";
Blockly.Msg.DELETE_BLOCK = "刪除塊";
Blockly.Msg.DELETE_X_BLOCKS = "刪除 %1 塊";
Blockly.Msg.DISABLE_BLOCK = "禁用塊";
Blockly.Msg.DUPLICATE_BLOCK = "複製";
Blockly.Msg.ENABLE_BLOCK = "啟用塊";
Blockly.Msg.EXPAND_ALL = "展開塊";
Blockly.Msg.EXPAND_BLOCK = "展開塊";
Blockly.Msg.EXTERNAL_INPUTS = "外部輸入";
Blockly.Msg.HELP = "幫助";
Blockly.Msg.INLINE_INPUTS = "單行輸入";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "創建空列表";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一個列表，長度為 0，不包含任何資料記錄";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "列表";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "增加、刪除或重新排列各部分以此重新配置這個清單塊。";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "建立字串使用";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "將一個項添加到列表中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一個具有任意數量項目的列表。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒數第#";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "獲得";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出並移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最後";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "隨機";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的項。#1是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "隨機返回列表中的一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除並返回列表中的第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除並返回列表中的指定位置的項。#1 是最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除並返回列表中的指定位置的項。#1 是第一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除並返回列表中的最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除並返回列表中的一個隨機項目中。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一項";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "刪除在列表中的指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的項。#1 是第一項。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最後一項";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "刪除列表中的一個隨機的項。";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到倒數第#";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到#";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到最後";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "從頭獲得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "從倒數#取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "從#取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "複製清單中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出第一個項出現";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出最後一個項出現";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一/最後一個匹配項的索引值。如果找不到項目則返回0。";
Blockly.Msg.LISTS_INLIST = "在列表中";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1是空的";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "如果改列表為空，則返回真。";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "%1的長度";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的長度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用項 %1 重複 %2 次";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重複次數的值的列表。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "為";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入在";
Blockly.Msg.LISTS_SET_INDEX_SET = "設置";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始處添加該項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中指定位置的項。#1是第一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "將該項追加到列表的末尾。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中隨機插入項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "設置列表中的第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "設置在列表中指定位置的項。#1是最後一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "設置在列表中指定位置的項。#1是第一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "設置列表中的最後一項。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "設置列表中一個隨機的項目。";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "昇冪";
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "降冪";
Blockly.Msg.LISTS_SORT_TITLE = "排序%1 %2 %3";
Blockly.Msg.LISTS_SORT_TOOLTIP = "排序一個清單的拷貝。";
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "按字母排序，忽略大小寫";
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "按數字排序";
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "按字母排序";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "從文本製作清單";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "從清單拆出文本";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "加入文本清單至一個文本，由分隔符號分隔。";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "拆分文本到文本清單，按每個分隔符號拆分。";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "用分隔符號";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "假";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回真或假。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果兩個輸入結果相等，則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一個輸入結果比第二個大，則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一個輸入結果大於或等於第二個輸入結果，則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一個輸入結果比第二個小，則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一個輸入結果小於或等於第二個輸入結果，則返回真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果兩個輸入結果不相等，則返回真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg.LOGIC_NEGATE_TITLE = "非%1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果輸入結果為假，則返回真；如果輸入結果為真，則返回假。";
Blockly.Msg.LOGIC_NULL = "空";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回空值。";
Blockly.Msg.LOGIC_OPERATION_AND = "和";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果兩個輸入結果都為真，則返回真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少有一個輸入結果為真，則返回真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "測試";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://zh.wikipedia.org/wiki/條件運算子";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果為假";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果為真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "檢查“test”中的條件。如果條件為真，則返回“if true”的值，否則，則返回“if false”的值。";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://zh.wikipedia.org/wiki/算術";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回兩個數字的和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回兩個數字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回兩個數字的區別。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回兩個數字的乘積。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第一個數的第二個數次冪。";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://zh.wikipedia.org/wiki/%E5%8A%A0%E6%B3%95";
Blockly.Msg.MATH_CHANGE_TITLE = "更改 %1 由 %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "將一個數添加到變數“%1”。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/數學常數";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一個常見常量：π (3.141......)，e (2.718...)、φ (1.618...)、 sqrt(2) (1.414......)、sqrt(½) (0.707......)或 ∞（無窮大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制數字 %1 介於 (低) %2 到 (高) %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制數位介於兩個指定的數字之間";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶數";
Blockly.Msg.MATH_IS_NEGATIVE = "為負";
Blockly.Msg.MATH_IS_ODD = "是奇數";
Blockly.Msg.MATH_IS_POSITIVE = "為正";
Blockly.Msg.MATH_IS_PRIME = "是質數";
Blockly.Msg.MATH_IS_TOOLTIP = "如果數字是偶數、奇數、非負整數、正數、負數或如果它可被某數字整除，則返回真或假。";
Blockly.Msg.MATH_IS_WHOLE = "為整數";
Blockly.Msg.MATH_MODULO_HELPURL = "https://zh.wikipedia.org/wiki/模除";
Blockly.Msg.MATH_MODULO_TITLE = "取餘數自 %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "返回這兩個數字相除後的餘數。";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://zh.wikipedia.org/wiki/數";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一個數字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "清單中的平均數";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "列表中的最大值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "列表中位數";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "列表中的最小值";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "清單模式";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "列表的隨機項";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "列表中的標準差";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "列表中的數的總和";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中的數值的平均值。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中最大數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中的中位數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中最小數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回列表中的最常見的項的列表。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "從清單中返回一個隨機的元素。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表的標準差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回清單中的所有數字的和。";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://zh.wikipedia.org/wiki/亂數產生器";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "隨機分數";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介於（包含）0.0到1.0之間的亂數。";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://zh.wikipedia.org/wiki/亂數產生器";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "從 %1 到 %2 之間的隨機整數";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "返回兩個指定的範圍（含）之間的隨機整數。";
Blockly.Msg.MATH_ROUND_HELPURL = "https://zh.wikipedia.org/wiki/數值修約";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "向下捨入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "向下捨入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "向上捨入";
Blockly.Msg.MATH_ROUND_TOOLTIP = "數字向上或向下捨入。";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "絕對";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "平方根";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回一個數的絕對值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回數的e次冪。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回一個數的自然對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回數字的對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回數的邏輯非。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回數的10次冪。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回數的平方根。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函數";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回一個數的反餘弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回一個數的反正弦值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
Blockly.Msg.ME = "我";
Blockly.Msg.NEW_VARIABLE = "新建變量...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新變數的名稱：";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "允許聲明";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "與：";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/副程式";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "運行使用者定義的函數“%1”。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://zh.wikipedia.org/wiki/副程式";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "運行使用者定義的函數“%1”，並使用它的輸出值。";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "與：";
Blockly.Msg.PROCEDURES_CREATE_DO = "創建“%1”";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "描述該功能...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/副程式";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "做點什麼";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "至";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "創建一個不帶輸出值的函數。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://zh.wikipedia.org/wiki/副程式";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "返回";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "創建一個有輸出值的函數。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函數具有重複參數。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "突出顯示函式定義";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值為真，則返回第二個值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 僅在定義函數內可使用此塊。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "輸入名稱：";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "添加函數輸入。";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "輸入";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "添加、刪除或重新排此函數的輸入。";
Blockly.Msg.REDO = "重做";
Blockly.Msg.REMOVE_COMMENT = "刪除注釋";
Blockly.Msg.RENAME_VARIABLE = "重命名變數...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "將所有“%1”變數重命名為:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "追加文本";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "將一些文本追加到變數“%1”。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "為小寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "為首字母大寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "為大寫";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小寫複製這段文字。";
Blockly.Msg.TEXT_CHARAT_FIRST = "獲得第一個字元";
Blockly.Msg.TEXT_CHARAT_FROM_END = "獲得倒數第#個字元";
Blockly.Msg.TEXT_CHARAT_FROM_START = "獲得字元#";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "于文本中";
Blockly.Msg.TEXT_CHARAT_LAST = "獲得最後一個字元";
Blockly.Msg.TEXT_CHARAT_RANDOM = "獲取隨機的字母";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位於指定位置的字母。";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "將一個項添加到文本中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、移除或重新排列各節來重新配置這個文字區塊。";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到倒數第#個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到字元#";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到最後一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自文本";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串自第一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自#到末尾";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自#";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分文本。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "自文本";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "尋找第一個出現的文本";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "尋找最後一個出現的文本";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二個字串中的第一/最後一個匹配項的索引值。如果未找到則返回 0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1是空的";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的文本為空，則返回真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "建立字串使用";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "通過串起任意數量的項以建立一段文字。";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "%1的長度";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回提供文本的字母數（包括空格）。";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "列印%1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "列印指定的文字、數位或其他值。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "提示使用者輸入數字。";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "提示使用者輸入一些文本。";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "輸入數位並顯示提示消息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "輸入數位並顯示提示消息";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://zh.wikipedia.org/wiki/字串";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "一個字母、單詞或一行文本。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除兩側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右側空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "複製這段文字的同時刪除兩端多餘的空格。";
Blockly.Msg.TODAY = "今天";
Blockly.Msg.UNDO = "撤銷";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "變量";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "創建“設定%1”";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此變數的值。";
Blockly.Msg.VARIABLES_SET = "賦值 %1 到 %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "創建“獲得%1”";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "設置此變數，以使它和輸入值相等。";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

Blockly.Msg.DOBOT_ON = "開";
Blockly.Msg.DOBOT_OFF = "關";
Blockly.Msg.Dobot_Speed = "速度";
Blockly.Msg.Dobot_DELTAPULSE = "增量脈衝"
Blockly.Msg.DOBOT_ENABELD = "使能控制";
Blockly.Msg.DOBOT_GripperON = "抓取";
Blockly.Msg.DOBOT_GripperOff = "張開";
Blockly.Msg.DOBOT_BASEIC_HOME = "回零";
Blockly.Msg.DOBOT_BASEIC_HOME_TOOLTIP = "讓機械臂碼盤回零";
Blockly.Msg.DOBOT_BASEIC_TIME = "獲取時間";
Blockly.Msg.DOBOT_BASEIC_TIME_TOOLTIP = "獲取當前時間，以秒為單位";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE = "選擇夾具";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_TOOLTIP = "選擇末端夾具的類型";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_SUCTIONCAP = "吸盤";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_GRIPPER = "手抓";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_LASER = "鐳射";
Blockly.Msg.DOBOT_BASEIC_SETENDTYPE_PEN = "筆";
Blockly.Msg.DOBOT_BASEIC_SETENDEFFECTORPARAMS = "設置末端坐標偏移量";//parekr add 2018 9 8
Blockly.Msg.DOBOT_BASEIC_SETENDEFFECTORPARAMS_TOOLTIP = "設置末端坐標偏移參數";
Blockly.Msg.DOBOT_SET_JOINT_SPEED_TOOLTIP = "設置每一個軸的速度和加速度";
Blockly.Msg.DOBOT_SET_LINEAR_SPEED = "設置線性速度";
Blockly.Msg.DOBOT_SET_LINEAR_SPEED_TOOLTIP = "設置運行的線性速度和加速度";
Blockly.Msg.DOBOT_SET_JUMP_HEIGHT = "設置門型高度";
Blockly.Msg.DOBOT_SET_JUMP_HEIGHT_TOOLTIP = "設置跳轉運行的高度";
Blockly.Msg.DOBOT_GOTO = "移動到點";
Blockly.Msg.DOBOT_GOTO_TOOLTIP = "移動到某一點";
Blockly.Msg.DOBOT_JUMPTO = "門型移動到某一點";
Blockly.Msg.DOBOT_JUMPTO_TOOLTIP = "門型移動到某一點";
Blockly.Msg.DOBOT_MOVE = "相對移動";
Blockly.Msg.DOBOT_MOVE_TOOLTIP = "相對移動某一點";
Blockly.Msg.DOBOT_SETR = "設置末端角度";
Blockly.Msg.DOBOT_SETR_TOOLTIP = "相對改變末端的角度";
Blockly.Msg.DOBOT_SET_JOINT_ANGLE = "按照角度來移動";
Blockly.Msg.DOBOT_SET_JOINT_ANGLE_TOOLTIP = "按照角度移動機械臂";
Blockly.Msg.DOBOT_SUCTIONCAP = "吸盤";
Blockly.Msg.DOBOT_SUCTIONCAP_TOOLTIP = "吸盤控制";
Blockly.Msg.DOBOT_GRIPPER = "手抓";
Blockly.Msg.DOBOT_GRIPPER_TOOLTIP = "手抓控制";
Blockly.Msg.DOBOT_GET_CURRETN_COORDINATE= "獲取目前的座標值";
Blockly.Msg.DOBOT_GET_CURRETN_COORDINATE_TOOLTIP = "獲取目前的座標值";
Blockly.Msg.DOBOT_GET_CURRENT_ANGLE= "獲取目前的角度值";
Blockly.Msg.DOBOT_GET_CURRENT_ANGLE_TOOLTIP = "獲取目前的角度值";
Blockly.Msg.DOBOT_DELAYTIME= "延遲";
Blockly.Msg.DOBOT_DELAYTIME_TOOLTIP = "延遲執行";
Blockly.Msg.DOBOT_MOTOR = "電機"
Blockly.Msg.DOBOT_Value = "獲取";
Blockly.Msg.DOBOT_FREQUENCY = "頻率";
Blockly.Msg.DOBOT_DUTYCYCLE = "占空比";

Blockly.Msg.DOBOT_joint1 = "關節1";
Blockly.Msg.DOBOT_joint2 = "關節2";
Blockly.Msg.DOBOT_joint3 = "關節3";
Blockly.Msg.DOBOT_joint4 = "關節4";
Blockly.Msg.DOBOT_xBias = "X偏移値";
Blockly.Msg.DOBOT_yBias = "Y偏移値";
Blockly.Msg.DOBOT_zBias = "Z偏移値";
Blockly.Msg.DOBOT_j1 = "關節1";
Blockly.Msg.DOBOT_j2 = "關節2";
Blockly.Msg.DOBOT_j3 = "關節3";
Blockly.Msg.DOBOT_j4 = "關節4";
Blockly.Msg.DOBOT_j1Velocity = "關節1速度";
Blockly.Msg.DOBOT_j2Velocity = "關節2速度";
Blockly.Msg.DOBOT_j3Velocity = "關節3速度";
Blockly.Msg.DOBOT_j4Velocity = "關節4速度";
Blockly.Msg.DOBOT_j1Acceleration = "關節1加速度";
Blockly.Msg.DOBOT_j2Acceleration = "關節2加速度";
Blockly.Msg.DOBOT_j3Acceleration = "關節3加速度";
Blockly.Msg.DOBOT_j4Acceleration = "關節4加速度";
Blockly.Msg.DOBOT_height = "高度";
Blockly.Msg.DOBOT_lVelocity = "l速度";
Blockly.Msg.DOBOT_lAcceleration = "l加速度";
Blockly.Msg.DOBOT_velocityRatio = "速度比率";
Blockly.Msg.DOBOT_accelerationRatio = "加速度比率";
Blockly.Msg.DOBOT_value = "數值";
Blockly.Msg.DOBOT_type = "類型";

Blockly.Msg.DOBOT_THRESHOLD = "閾值";
Blockly.Msg.DOBOT_ANGLEUNIT = "度";
Blockly.Msg.DOBOT_SETLOSTSTEPPARAMS_TOOLTIP = "設置丟步參數";
Blockly.Msg.DOBOT_SETLOSTSTEPCMD_TOOLTIP = "丟步檢測";
Blockly.Msg.DOBOT_SETINFRAREDSENEOR = "設置紅外感應器";
Blockly.Msg.DOBOT_SETINFRAREDSENEOR_TOOLTIP = "設置紅外感應器";
Blockly.Msg.DOBOT_GETINFRAREDSENEOR = "獲取紅外感應器";
Blockly.Msg.DOBOT_GETINFRAREDSENEOR_TOOLTIP = "獲取紅外感應器";
Blockly.Msg.Dobot_DISTANCE = "距離";
Blockly.Msg.Dobot_IO_INPUT_3V = "輸入 3.3V";
Blockly.Msg.Dobot_IO_INPUT_5V = "輸入 5V";
Blockly.Msg.Dobot_IO_ADC = "輸入 AD";
Blockly.Msg.Dobot_IO_OUTPUT_3V = "輸出 3.3V";
Blockly.Msg.Dobot_IO_OUTPUT_5V = "輸出 5V";
Blockly.Msg.Dobot_IO_OUTPUT_12V = "輸出 12V";
Blockly.Msg.Dobot_IO_PWM = "輸出 PWM";
Blockly.Msg.DOBOT_ACCELERATION = "加速度";
Blockly.Msg.DOBOT_VELOCITY = "速度";

//2017-07-03
Blockly.Msg.DOBOT_SET_JOINT_SPEED = "設置軸速度";
Blockly.Msg.DOBOT_SET_JOINT_SPEED_TOOLTIP = "設置軸速度";
Blockly.Msg.DOBOT_SET_LINEAR_SPEED = "設置運動比例";
Blockly.Msg.DOBOT_SET_LINEAR_SPEED_TOOLTIP = "設置運動比例";
Blockly.Msg.DOBOT_VELOCITY_RATIO = "速度比例";
Blockly.Msg.DOBOT_ACCELERATION_RATIO = "加速度比例";
Blockly.Msg.DOBOT_SET_MOTOR = "設置電機速度"
Blockly.Msg.DOBOT_SET_MOTOR_TOOLTIP = "設置電機速度"
Blockly.Msg.DOBOT_SET_MOTORS = "設置電機速度和移動距離"
Blockly.Msg.DOBOT_SET_MOTORS_TOOLTIP = "設置電機速度和距離"
Blockly.Msg.DOBOT_GOTO = "移動到";
Blockly.Msg.DOBOT_GOTO_TOOLTIP = "移動到一個絕對笛卡爾座標位置";
Blockly.Msg.DOBOT_JUMPTO = "門型運動到";
Blockly.Msg.DOBOT_JUMPTO_TOOLTIP = "門型運動到一個絕對笛卡爾座標位置";
Blockly.Msg.DOBOT_MOVE = "相對移動";
Blockly.Msg.DOBOT_MOVE_TOOLTIP = "相對移動一個相對笛卡爾座標增量";
Blockly.Msg.DOBOT_SET_JOINT_ANGLE = "設置軸角度";
Blockly.Msg.DOBOT_SET_JOINT_ANGLE_TOOLTIP = "設置軸角度";
Blockly.Msg.DOBOT_SET_INFRARED_SENEOR = "設置顏色感應器";
Blockly.Msg.DOBOT_SET_INFRARED_SENEOR_TOOLTIP = "設置顏色感應器";
Blockly.Msg.DOBOT_GET_INFRARED_SENEOR = "獲取顏色感應器數值";
Blockly.Msg.DOBOT_GET_INFRARED_SENEOR_TOOLTIP = "檢測感應器前方一定距離是否有物體，有物體時為1；沒有物體時為0；";
Blockly.Msg.DOBOT_SET_COLORSENEOR= "設置顏色感應器";
Blockly.Msg.DOBOT_SET_COLORSENEOR_TOOLTIP = "設置顏色感應器";
Blockly.Msg.DOBOT_GET_COLORSENEOR= "識別顏色";
Blockly.Msg.DOBOT_GET_COLORSENEOR_TOOLTIP = "用於識別3種基本的顏色：藍色、綠色、紅色。當檢測該顏色時返回1，否則返回0。";
Blockly.Msg.DOBOT_SET_CONVEYOR = "設置傳送帶"
Blockly.Msg.DOBOT_SET_CONVEYOR_TOOLTIP = "設置傳送帶"
Blockly.Msg.DOBOT_SET_LINEAR_RAIL = "設置滑軌"
Blockly.Msg.DOBOT_SET_LINEAR_RAIL_TOOLTIP = "設置滑軌"
Blockly.Msg.DOBOT_SETL = "移動滑軌到";
Blockly.Msg.DOBOT_SETL_TOOLTIP = "移動滑軌到一個絕對笛卡爾座標位置";
Blockly.Msg.DOBOT_SET_L_SPEED = "設置滑軌速度";
Blockly.Msg.DOBOT_SET_L_SPEED_TOOLTIP = "設置滑軌的速度和加速度";
Blockly.Msg.DOBOT_POWER = "功率";
Blockly.Msg.DOBOT_LASER = "鐳射";
Blockly.Msg.DOBOT_LASER_TOOLTIP = "鐳射";
Blockly.Msg.DOBOT_SET_OUTPUT12V = "設置12V輸出   EIO";
Blockly.Msg.DOBOT_SET_OUTPUT12V_TOOLTIP = "設置12V輸出";
Blockly.Msg.DOBOT_SET_OUTPUT= "設置電壓輸出   EIO";
Blockly.Msg.DOBOT_SET_OUTPUT_TOOLTIP = "設置電壓輸出";
Blockly.Msg.DOBOT_GET_INPUT_EIO= "獲取電壓輸入   EIO";
Blockly.Msg.DOBOT_GET_INPUT_EIO_TOOLTIP = "獲取電壓輸入";
Blockly.Msg.DOBOT_SET_PWM = "設置PWM輸出   EIO";
Blockly.Msg.DOBOT_SET_PWM_TOOLTIP = "設置PWM輸出";
Blockly.Msg.DOBOT_GET_ADC = "獲取AD輸入   EIO";
Blockly.Msg.DOBOT_GET_ADC_TOOLTIP = "獲取AD輸入";
Blockly.Msg.DOBOT_SET_IOMULTIPLEXING= "設置EIO類型";
Blockly.Msg.DOBOT_SET_IOMULTIPLEXING_TOOLTIP = "設置EIO類型";

//2017-09-27
Blockly.Msg.DOBOT_SET_COORDINATE_SPEED = "設置笛卡爾座標系速度";
Blockly.Msg.DOBOT_SET_COORDINATE_SPEED_TOOLTIP = "設置笛卡爾座標系速度";

//2018-04-21
Blockly.Msg.DOBOT_SET_OUTPUT5V = "設置5V輸出   EIO";
Blockly.Msg.DOBOT_SET_OUTPUT5V_TOOLTIP = "設置5V输出";

//2018-06-06
Blockly.Msg.DOBOT_PORT = "端口";
Blockly.Msg.DOBOT_HARDWARE = "硬件";
Blockly.Msg.DOBOT_NEW = "V2";
Blockly.Msg.DOBOT_OLD = "V1";
Blockly.Msg.DOBOT_VERSION = "版本";
